formatter: "markdown table"

sort:
  enabled: true
  by: required

content: |-
  {{ .Requirements }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Resources }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- begin-tf-docs -->
    {{ .Content }}
    <!-- end-tf-docs -->
